### ISSUE TITLE
Integration loses entities following power cut (and presumably new IP address for the Hot Tub)

### ISSUE THREAD

**Issue by james-rival** [cdpuk/ha-bestway#70]
This is a great integration which I've used daily for the last few months for controlling the Hot Tub and for contributing to automations.

Version 1.6
Lay-Z-Spa Toronto

Following a brief power cut which tripped the RCD on the Hot Tub (and presumably the Hot Tub getting assigned a new IP address by the router when I reset the RCD an hour later), the HA integration would not show any entity content and I couldn't control or monitor the Hot Tub at all.  The Bestway App still worked fine.  I tried various things: reloaded the integration, restarted HA, removed and re-added device in the integration, reinstalled the Bestway App, none of which got the entities working in HA.  What finally worked was deleting the Hot Tub as a device in the Bestway App, and then adding it again.  The integration in Home Assistant then picked everything up correctly.

Should the integration maintain contact with the device and entities even if the IP address changes, as the Bestway App appears to do?  Was there a smarter way I missed of getting it working again?

**Comment by cdpuk** [comment]
The integration talks to the cloud API, so the local IP address shouldn't matter. I can't think of a reason for this behaviour, and certainly haven't observed it myself through many power cycles. I suggest if it happens again you attempt to collect some debug logs to see what data the cloud API is providing us. Chances are it's a cloud problem and we can't do much about that. I believe the Bestway app is able to establish a direct connection to the spa when on the same Wi-Fi network, so that might explain why it continued to work.

I'll close this for now, but feel free to reopen/report if new information is available.
