### ISSUE TITLE
No data available for device

### ISSUE THREAD

**Issue by crankeith** [cdpuk/ha-bestway#73]
## Version of the custom_component
latest

## Bestway device

Saluspa Coronado Airjet_V01

## Describe the bug

The connection seems to be successful according to the logs but no data is being returned.

## Logs

```text

2024-09-05 09:09:46.022 DEBUG (MainThread) [custom_components.bestway.bestway.api] Device list refreshed: {"devices": [{"protoc": 3, "ws_port": 8080, "port_s": 8883, "gw_did": null, "host": "usm2m.gizwits.com", "sleep_duration": 3600, "port": 1883, "mcu_soft_version": "D4H90227", "product_key": "********************************", "state_last_timestamp": 1725021301, "role": "owner", "is_sandbox": false, "type": "normal", "product_name": "Airjet_V01", "is_disabled": false, "mcu_hard_version": "P4960011", "wifi_soft_version": "04X3000B", "dev_alias": "Hot Tub", "mesh_id": null, "is_online": false, "dev_label": [], "wss_port": 8880, "remark": "25", "did": "**********************", "mac": "************", "passcode": "**********", "wifi_hard_version": "0ESP32C3", "is_low_power": false}]}
2024-09-05 09:09:46.126 DEBUG (MainThread) [custom_components.bestway.bestway.api] No data available for device u3htQ3EEzlzn6Ii6HejnQl
2024-09-05 09:09:46.126 DEBUG (MainThread) [custom_components.bestway.coordinator] Finished fetching Bestway API data in 0.375 seconds (success: True)

```

**Comment by WelshRocketman** [comment]
My observation here is that the spa is returning "is_online" as false. I found that the device is found and the integration seems to successfully setup but then you never find any further updates.

I ended up forking this integration to test my theory and modified the code for the entity (in entity.py) to always return true for the available() property and not use the online status from the api response. This works and is the code I am currently running.

I haven't really had the opportunity to work out why the api is saying the device is offline because it clearly isn't. I haven't found a better way to determine if the device is available. Maybe others have some ideas?

**Comment by jonthesticks** [comment]
@WelshRocketman Did you ever get to the bottom of this? I'm seeing this same issue having just moved my Milan spa over from the Lay Z Spa app to the Bestway app. I've tried repeating the registration process several times but it's always the same. Debug logs show _"is_online": false_ exactly as you describe.

What's interesting is that this problem is also evident in the Bestway mobile app when the phone isn't connected to the same local Wi-Fi as the spa. If I turn Wi-Fi off and use 5G instead for example, the app greys out the data, overlays a Product Offline error message and inhibits control. You can, however, still see the data updating in the background. As an example, if I change the set temperature, I can see it updating live. So it feels like the app is also seeing that erroneous offline flag but it doesn't seem to be happening when connected locally.

**Comment by WelshRocketman** [comment]
> @WelshRocketman Did you ever get to the bottom of this? I'm seeing this same issue having just moved my Milan spa over from the Lay Z Spa app to the Bestway app. I've tried repeating the registration process several times but it's always the same. Debug logs show _"is_online": false_ exactly as you describe.
> 
> What's interesting is that this problem is also evident in the Bestway mobile app when the phone isn't connected to the same local Wi-Fi as the spa. If I turn Wi-Fi off and use 5G instead for example, the app greys out the data, overlays a Product Offline error message and inhibits control. You can, however, still see the data updating in the background. As an example, if I change the set temperature, I can see it updating live. So it feels like the app is also seeing that erroneous offline flag but it doesn't seem to be happening when connected locally.

I resolved the issue by creating a fork of the code and telling it to ignore the spa status and always assume it was online (given that most of the time it is). I haven't spent enough time assessing the state change in the data to see if there is another status that would be better to use.

**Comment by crankeith** [comment]
> My observation here is that the spa is returning "is_online" as false. I found that the device is found and the integration seems to successfully setup but then you never find any further updates.
> 
> I ended up forking this integration to test my theory and modified the code for the entity (in entity.py) to always return true for the available() property and not use the online status from the api response. This works and is the code I am currently running.
> 
> I haven't really had the opportunity to work out why the api is saying the device is offline because it clearly isn't. I haven't found a better way to determine if the device is available. Maybe others have some ideas?
> 
> It might be that the is_disabled might be a better way to set this property.

Thanks for the tip. I have forked and done the same thing and it works.

**Comment by cdpuk** [comment]
This sounds a lot like a device or API bug. This has been the only report so far, but if more reports come in with a pattern, e.g. same device or software versions, then some sort of edge case could be added to the logic. Right now I'm a bit reluctant to do that for fear of confusing all other users whose devices correctly report the `is_offline` flag.
